---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rsrini83/my-gitops.git
    targetRevision: HEAD
    path: dev/apps/app2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
